# Generated by Django 3.2.23 on 2023-12-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='../rjstswgoqpakct7vhsy7', upload_to='images/'),
        ),
    ]
