# Generated by Django 3.2.23 on 2023-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
