# Generated by Django 3.2.23 on 2023-12-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('importance', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('crucial', 'Crucial')], default='low', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='tasks_collaborated', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
